### ISSUE TITLE
Choices change when is equal to the value

### ISSUE THREAD

**Issue by qav-gabriela-castro** [surveyjs/editor#415] opened 2018-09-21 12:45 UTC
### Are you requesting a feature, reporting a bug or ask a question?

reporting a bug

### What is the current behavior?

Hi, I'm creating a form using the surveyjs 1.0.43 with this structure :
"choices": [
{
"value": "OUI",
"text": {
"fr": "OUI",
"default": "YES",
"es": "SÍ",
"nl": "JA",
"it": "SÌ"
}
},
{
"value": "NON",
"text": {
"fr":"NON",
"default": "NO",
"nl": "NEE"
}
}
]
when i edit the question with the editor, it removes the fr translation because it's equal to the "value". there's a way to correct that bug ?

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by dmitrykurmanov** [comment] 2018-09-21 13:12
duplicate of https://surveyjs.answerdesk.io/internal/ticket/details/T1087

**Comment by dmitrykurmanov** [comment] 2018-09-21 13:14
@qav-gabriela-castro please don't duplicate the issues in github and support center :) We are followwing both resources.

**Closed by dmitrykurmanov** 2018-09-21 13:14 UTC
