### ISSUE TITLE
Change "For more details please check the documentation" for customURL

### ISSUE THREAD

**Issue by SammaniPalan** [surveyjs/editor#342] opened 2018-05-15 07:34 UTC
### Are you requesting a feature, reporting a bug or ask a question?

Question

### What is the current behavior?
When we click on "For more details please check the documentation" in question edit form it goes to
"https://surveyjs.io/Documentation/LibraryParameter?id=QuestionBase&parameter=visibleIf"

![image](https://user-images.githubusercontent.com/20948377/40042898-7abbd1ca-5840-11e8-959a-b0bbae5a7a77.png)

### What is the expected behavior?

We want to change that link to redirect user to a custom URL where it has a custom guideline document which our client has created

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:Chrome, Edge
* editor version:

**Comment by tsv2013** [comment] 2018-05-15 07:36
@SammaniPalan From the next version v1.0.22, you will be able to change the url as:
SurveyEditor.defaultStrings.pe.conditionShowMoreUrl = "YourUrl";
to hide it set this attribute to emtpy string or null
SurveyEditor.defaultStrings.pe.conditionShowMoreUrl = "";

We will likely release a new minor version today.

PS: Please post issues about SurveyJS Editor into this Repo

Thank you,
Andrew

**Comment by tsv2013** [comment] 2018-05-15 07:36
Duplicate of the https://github.com/surveyjs/surveyjs/issues/1095 issue

**Closed by tsv2013** 2018-05-15 07:36 UTC
