### ISSUE TITLE
Validators are broken: 1. minValue, 2. UI

### ISSUE THREAD

**Issue by sco2tbold** [surveyjs/editor#237] opened 2017-12-12 10:54 UTC
1. For the question porperty "validator" and for a numeric validator, the minValue property is not stored. Please see screenshot 1.

![image](https://user-images.githubusercontent.com/7213039/33880648-97a4353e-df32-11e7-865c-edd65747f5af.png)

2. For the items validators in the dialogue the "+" does not do anything. Please see screenshot 2.

![image](https://user-images.githubusercontent.com/7213039/33880774-fd89b946-df32-11e7-9917-a28b9f00a2a4.png)

**Comment by andrewtelnov** [comment] 2017-12-12 19:41
@sco2tbold The second issue was fixed in v0.98.3 that we have released several hours ago.
We could not reproduced the first version though.

Thank you,
Andrew

**Comment by sco2tbold** [comment] 2017-12-13 15:12
Thanks Andrew. Problem #2 isn't there anymore in the version you mentioned. 

There's one other thing - not sure if it's related to it. I've got a simple "Multiple text" field with 2 items; both are of type "Numeric". When I test this config and enter numbers, I get a validation error "Must be numeric".

![image](https://user-images.githubusercontent.com/7213039/33945684-fed3ab16-e01f-11e7-8670-478407068523.png)

Here's the config. 

`{
 "pages": [
  {
   "elements": [
    {
     "type": "multipletext",
     "isRequired": true,
     "items": [
      {
       "name": "count",
       "inputType": "number",
       "title": "Number involved"
      },
      {
       "name": "total",
       "inputType": "number",
       "title": "Total number found"
      }
     ],
     "name": "sugery_pathology_number_positive_lymph_nodes",
     "title": "Number of positive lymph nodes",
     "validators": [
      {
       "type": "numeric",
       "text": "asdf",
       "maxValue": 100
      }
     ]
    }
   ],
   "name": "page1"
  }
 ]
}`

**Closed** 2017-12-15 08:31 UTC
Labels: bug, fixed
