### ISSUE TITLE
Mandatory question on survey

### ISSUE THREAD

**Issue by xiuzhen1103** [surveyjs/editor#330] opened 2018-04-24 11:42 UTC
### Are you requesting a feature, reporting a bug or ask a question?
Ask a question

### What is the current behavior?
When a question marked as mandatory, after submit survey, error message appears indicates "Please answer the question." If user come back and fill in this question, error message still appear. 

### What is the expected behavior?
When a question marked as mandatory, after submit survey, error message appears indicates "Please answer the question." If user come back and fill in this question, error message should disappear.
Is there any chance you could make it responsive?

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/?p=preview

**Comment by tsv2013** [comment] 2018-04-24 11:48
The plunker link you provided is empty

**Comment by tsv2013** [comment] 2018-04-25 07:29
I'm closing this as a duplicate of the https://github.com/surveyjs/surveyjs/issues/1062

**Closed by tsv2013** 2018-04-25 07:29 UTC
Labels: couldn't reproduce
