### ISSUE TITLE
Show/Hide choices

### ISSUE THREAD

**Issue by AhmedAglan** [surveyjs/editor#289] opened 2018-03-01 10:20 UTC
### Are you requesting a feature, reporting a bug or ask a question?
Feature

### What is the expected behavior?
In multiple choices question, how to hide or show choices in a question based on selected/deselected choices of previous question ?

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by andrewtelnov** [comment] 2018-03-01 12:47
@AhmedAglan We have this suggestion in our TODO. Add visibleIf on choices item level.
Right now, the only way to implement it, is to have several questions with different names and choices, but with the same valueName.

Thank you,
Andrew

**Comment by tsv2013** [comment] 2018-03-02 07:44
Duplicate of the https://github.com/surveyjs/surveyjs/issues/676 - Visible if for answer choices

**Closed by tsv2013** 2018-03-02 07:44 UTC
Labels: duplicate, question

**Comment by andrewtelnov** [comment] 2018-05-15 11:40
@AhmedAglan It has been impelemented. More information is [here](https://github.com/surveyjs/surveyjs/issues/1079)

Thank you,
Andrew
