### ISSUE TITLE
Not working on Firefox 51 and up

### ISSUE THREAD

**Issue by elkinporras** [surveyjs/editor#175] opened 2017-10-19 14:57 UTC
### Are you requesting a feature, reporting a bug or ask a queation?

Reporting a bug

### What is the current behavior?

Editor and survey are not working on Firefox 51 and up.

### What is the expected behavior?

Working on any version of Firefox.

### How would you reproduce the current behavior (if this is a bug)?

TypeError: _this.sheet.addRule is not a function  survey.ko.js:14721:80
TypeError: __WEBPACK_IMPORTED_MODULE_3_survey_knockout__ is undefined  surveyeditor.js:4280:1
ReferenceError: SurveyEditor is not defined

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjs.io/Editor/Editor/

### Specify your

* browser: Firefox 51 and up
* editor version:  0.12.33

**Comment by tsv2013** [comment] 2017-10-24 12:30
Looks like a duplicate of the https://github.com/surveyjs/surveyjs/issues/726 issue.

**Closed** 2017-12-15 08:16 UTC
Labels: bug, duplicate
