### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by Khaledmohi** [surveyjs/editor#290] opened 2018-03-01 10:59 UTC
### Are you requesting a feature, reporting a bug or ask a question?
Feature

### What is the current behavior?

How can I validate more than one question is a survey, and based on result I can Exit/Complete survey?

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by dmitrykurmanov** [comment] 2018-03-01 11:22
I think that you need `onValidateQuestion ` event for validtating more than one question, please see the example: https://surveyjs.io/Examples/Library/?id=validators-event&platform=jQuery&theme=default . 

And for end of the survey please see `doComplete` method https://surveyjs.io/Documentation/Library/?id=surveymodel#doComplete

**Comment by andrewtelnov** [comment] 2018-03-27 12:48
The issue is likely solved and I'm closing it.

**Closed by andrewtelnov** 2018-03-27 12:48 UTC
Labels: question
