### ISSUE TITLE
compatibility

### ISSUE THREAD

**Issue by pierrecharlesp** [surveyjs/editor#75] opened 2017-04-06 13:13 UTC
Thanks for great job.
Which version of firefox is compatible with survey.js ? 
I meet issues with VisibleIf property and firefox ESR 45.3.
VisibleIF isn't working. Page doesn't appear.

Many thanks.

**Comment by andrewtelnov** [comment] 2017-04-06 13:25
@pierrecharlesp What version of surveyjs do you using? react. jquery, knockout?

Thank you,
Andrew

**Comment by pierrecharlesp** [comment] 2017-04-06 13:36
jquery

**Comment by pierrecharlesp** [comment] 2017-04-06 13:36
do you advice me to use React or Knockout ?

**Comment by andrewtelnov** [comment] 2017-04-06 14:33
@pierrecharlesp we will investigate the issue. @tsv2013 is working on it: https://github.com/surveyjs/surveyjs/issues/322

**Comment by tsv2013** [comment] 2017-04-10 07:28
@pierrecharlesp All SurveyJS library platfroms should work identically. Editor uses KnockoutJS internally. I'm closing this as a duplicate of https://github.com/surveyjs/surveyjs/issues/322. Could you please check updated thread?

**Closed by tsv2013** 2017-04-10 07:28 UTC
Labels: duplicate, question
